# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CoffeeBot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic 	frameworks
  use_frameworks!

	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'Firebase'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'

end
